/* ================================================================
   questions.js — 題庫資料 & 主題 metadata
   CalcMaster 98 微積分練習系統
================================================================ */

const QUESTION_DB = {
  limits: [
    { q: "求極限：lim(x→2) (x² - 4) / (x - 2)", a: "4", opts: ["2","4","0","∞"],
      explain: "因式分解：(x²-4)/(x-2) = (x+2)(x-2)/(x-2) = x+2，代入 x=2 得 4。",
      hint: "嘗試因式分解分子", diff: "easy", topic: "極限" },
    { q: "求極限：lim(x→0) sin(x) / x", a: "1", opts: ["0","1","∞","不存在"],
      explain: "這是著名的三角函數極限，lim(x→0) sin(x)/x = 1，是微積分中最基本的極限之一。",
      hint: "這是一個標準結果，需要記住", diff: "easy", topic: "極限" },
    { q: "求極限：lim(x→∞) (3x² + 2x) / (x² + 5)", a: "3", opts: ["2","3","5","∞"],
      explain: "分子分母同除 x²，得 (3 + 2/x) / (1 + 5/x²)，當 x→∞ 時，2/x 和 5/x² 趨近於 0，結果為 3/1 = 3。",
      hint: "分子分母同除最高次項 x²", diff: "easy", topic: "極限" },
    { q: "求極限：lim(x→0) (1 - cos x) / x²", a: "1/2", opts: ["0","1/2","1","2"],
      explain: "使用 L'Hôpital 法則或泰勒展開：cos x ≈ 1 - x²/2，代入得 (x²/2)/x² = 1/2。",
      hint: "使用 cos x 的泰勒展開", diff: "med", topic: "極限" },
    { q: "若 lim(x→3) f(x) = 5，lim(x→3) g(x) = 2，則 lim(x→3) [f(x)·g(x)] = ?", a: "10", opts: ["7","10","3","15"],
      explain: "極限的乘法法則：lim[f(x)·g(x)] = lim f(x) · lim g(x) = 5 × 2 = 10",
      hint: "使用極限的乘法法則", diff: "easy", topic: "極限" },
    { q: "求極限：lim(x→2) (x³ - 8) / (x - 2)", a: "12", opts: ["4","8","12","6"],
      explain: "因式分解：x³-8 = (x-2)(x²+2x+4)，化簡後代入 x=2：4+4+4 = 12。",
      hint: "立方差公式：a³-b³=(a-b)(a²+ab+b²)", diff: "med", topic: "極限" },
  ],

  lhopital: [
    { q: "用 L'Hôpital 法則求：lim(x→0) (e^x - 1) / x", a: "1", opts: ["0","1","e","∞"],
      explain: "0/0 不定型，對分子分母分別求導：e^x / 1，代入 x=0 得 e^0 = 1。",
      hint: "先確認是 0/0 型，再對分子分母求導", diff: "med", topic: "L'Hôpital" },
    { q: "用 L'Hôpital 法則求：lim(x→0) sin(3x) / x", a: "3", opts: ["1","2","3","0"],
      explain: "0/0 型，對分子分母求導：3cos(3x)/1，代入 x=0 得 3cos(0) = 3。",
      hint: "d/dx[sin(3x)] = 3cos(3x)", diff: "med", topic: "L'Hôpital" },
    { q: "用 L'Hôpital 法則求：lim(x→∞) ln(x) / x", a: "0", opts: ["0","1","∞","不存在"],
      explain: "∞/∞ 型，對分子分母求導：(1/x)/1 = 1/x，當 x→∞ 時趨近 0。",
      hint: "d/dx[ln x] = 1/x", diff: "med", topic: "L'Hôpital" },
  ],

  continuity: [
    { q: "函數 f(x) = (x²-9)/(x-3) 在 x=3 是否連續？", a: "不連續（但可補充定義）",
      opts: ["連續","不連續（但可補充定義）","不連續（無法補救）","需要更多資訊"],
      explain: "x=3 時分母為 0，函數無定義，所以在 x=3 不連續。但可補充定義 f(3)=6（因為 lim(x→3) f(x) = 6），使之連續。",
      hint: "先求極限，再看函數值", diff: "easy", topic: "連續性" },
    { q: "連續函數必要條件：f(a) 存在、lim(x→a) f(x) 存在、且？", a: "兩者相等",
      opts: ["f(a)=0","兩者相等","極限為正","函數可微"],
      explain: "連續性的定義：f 在 x=a 連續 ⟺ f(a) 存在、lim(x→a)f(x) 存在，且 lim(x→a)f(x) = f(a)。",
      hint: "回想連續性的完整定義", diff: "easy", topic: "連續性" },
  ],

  derivative: [
    { q: "根據導數定義，f'(x) = lim(h→0) ?", a: "[f(x+h) - f(x)] / h",
      opts: ["[f(x+h) - f(x)] / h","[f(x) - f(h)] / x","f(x+h) · h","f(x) / h"],
      explain: "導數的正式定義是極限：f'(x) = lim(h→0) [f(x+h) - f(x)] / h，代表函數在某點的瞬間變化率。",
      hint: "這是導數的正式定義", diff: "easy", topic: "導數定義" },
    { q: "用定義求 f(x) = x² 在 x=3 的導數 f'(3) = ?", a: "6", opts: ["3","6","9","12"],
      explain: "f'(x) = lim(h→0) [(x+h)²-x²]/h = lim(h→0) [2xh+h²]/h = lim(h→0) (2x+h) = 2x\n代入 x=3：f'(3) = 6",
      hint: "展開 (x+h)² 後化簡", diff: "med", topic: "導數定義" },
  ],

  diff_rules: [
    { q: "d/dx [x⁵] = ?", a: "5x⁴", opts: ["5x⁴","x⁴","5x⁵","4x⁵"],
      explain: "冪次法則：d/dx[xⁿ] = n·xⁿ⁻¹，所以 d/dx[x⁵] = 5·x⁴。",
      hint: "冪次法則：指數提前乘，指數減一", diff: "easy", topic: "微分法則" },
    { q: "d/dx [sin x] = ?", a: "cos x", opts: ["cos x","-cos x","sin x","-sin x"],
      explain: "三角函數基本導數：d/dx[sin x] = cos x，需要牢記。",
      hint: "三角函數的基本導數", diff: "easy", topic: "微分法則" },
    { q: "d/dx [e^x] = ?", a: "e^x", opts: ["e^x","xe^(x-1)","ln x","1/x"],
      explain: "指數函數 e^x 的特殊性質：它的導數就是自身！d/dx[e^x] = e^x。",
      hint: "e^x 的導數有什麼特殊性？", diff: "easy", topic: "微分法則" },
    { q: "d/dx [ln x] = ?", a: "1/x", opts: ["1/x","ln x","x","1/ln x"],
      explain: "自然對數的導數：d/dx[ln x] = 1/x，這是非常常用的公式。",
      hint: "對數函數的導數公式", diff: "easy", topic: "微分法則" },
    { q: "d/dx [x³ + 2x - 5] = ?", a: "3x² + 2", opts: ["3x² + 2","3x + 2","x² + 2","3x² - 5"],
      explain: "對每項分別微分：d/dx[x³]=3x²、d/dx[2x]=2、d/dx[-5]=0，相加得 3x²+2。",
      hint: "對每項分別使用冪次法則", diff: "easy", topic: "微分法則" },
    { q: "若 f(x) = 3x⁴ - 2x² + 7，則 f'(x) = ?", a: "12x³ - 4x",
      opts: ["12x³ - 4x","12x³ - 4x + 7","3x³ - 2x","12x⁴ - 4x²"],
      explain: "逐項微分：d/dx[3x⁴]=12x³，d/dx[-2x²]=-4x，d/dx[7]=0，結果：12x³-4x。",
      hint: "常數項的導數為 0", diff: "easy", topic: "微分法則" },
    { q: "d/dx [cos x] = ?", a: "-sin x", opts: ["sin x","-sin x","cos x","-cos x"],
      explain: "d/dx[cos x] = -sin x，注意負號！與 sin x 的導數 cos x 相比多了負號。",
      hint: "注意正負號！", diff: "easy", topic: "微分法則" },
    { q: "d/dx [x · sin x] = ?（乘積法則）", a: "sin x + x cos x",
      opts: ["cos x","sin x + x cos x","x cos x","sin x · cos x"],
      explain: "乘積法則：d/dx[uv] = u'v + uv'\nu = x → u' = 1；v = sin x → v' = cos x\n結果：1·sin x + x·cos x = sin x + x cos x",
      hint: "乘積法則：(uv)' = u'v + uv'", diff: "med", topic: "微分法則" },
  ],

  chain_rule: [
    { q: "d/dx [sin(x²)] = ?", a: "2x cos(x²)", opts: ["cos(x²)","2x cos(x²)","2cos(x²)","x cos(x²)"],
      explain: "鏈鎖法則：外層 sin 的導數是 cos，內層 x² 的導數是 2x，相乘得 cos(x²) · 2x = 2x cos(x²)。",
      hint: "外層求導 × 內層求導", diff: "med", topic: "鏈鎖法則" },
    { q: "d/dx [e^(3x)] = ?", a: "3e^(3x)", opts: ["e^(3x)","3e^(3x)","3xe^(3x)","e^(3x)/3"],
      explain: "鏈鎖法則：外層 e^u 導數為 e^u，內層 3x 導數為 3，結果：e^(3x) · 3 = 3e^(3x)。",
      hint: "外層 e^u 求導仍是 e^u，再乘內層導數", diff: "med", topic: "鏈鎖法則" },
    { q: "d/dx [(x² + 1)⁵] = ?", a: "10x(x² + 1)⁴",
      opts: ["5(x²+1)⁴","10x(x² + 1)⁴","2x(x²+1)⁴","5x(x²+1)⁴"],
      explain: "鏈鎖法則：外層 u⁵ 導數是 5u⁴，內層 x²+1 導數是 2x，相乘得 5(x²+1)⁴ · 2x = 10x(x²+1)⁴。",
      hint: "先對外層冪次求導，再乘內層導數", diff: "med", topic: "鏈鎖法則" },
  ],

  implicit: [
    { q: "對 x² + y² = 25 進行隱函數微分，dy/dx = ?", a: "-x/y",
      opts: ["-x/y","x/y","-y/x","y/x"],
      explain: "對兩邊對 x 微分：2x + 2y(dy/dx) = 0，解出 dy/dx = -2x/(2y) = -x/y。",
      hint: "對 y 微分時要乘上 dy/dx（鏈鎖法則）", diff: "med", topic: "隱函數微分" },
    { q: "對 x³ + y³ = 6xy 進行隱函數微分，dy/dx = ?", a: "(2y - x²) / (y² - 2x)",
      opts: ["(2y - x²) / (y² - 2x)","(x² - 2y) / (y² - 2x)","3x²/3y²","y/x"],
      explain: "對兩邊微分：3x² + 3y²(dy/dx) = 6y + 6x(dy/dx)，整理：(3y²-6x)(dy/dx) = 6y-3x²，dy/dx = (2y-x²)/(y²-2x)。",
      hint: "對乘積項用乘積法則", diff: "hard", topic: "隱函數微分" },
  ],

  integral_basic: [
    { q: "∫ x³ dx = ?", a: "x⁴/4 + C", opts: ["x⁴/4 + C","3x² + C","4x³ + C","x⁴ + C"],
      explain: "反冪次法則：∫xⁿ dx = xⁿ⁺¹/(n+1) + C，代入 n=3：x⁴/4 + C。",
      hint: "反冪次法則：指數加一，除以新指數", diff: "easy", topic: "不定積分" },
    { q: "∫ cos x dx = ?", a: "sin x + C", opts: ["sin x + C","-sin x + C","cos x + C","-cos x + C"],
      explain: "基本積分公式：∫cos x dx = sin x + C（可以驗證：d/dx[sin x] = cos x）。",
      hint: "想想哪個函數微分後得到 cos x", diff: "easy", topic: "不定積分" },
    { q: "∫ e^x dx = ?", a: "e^x + C", opts: ["e^x + C","xe^x + C","e^x/x + C","ln(e^x) + C"],
      explain: "e^x 積分後仍是 e^x + C，這是它的特殊性質。",
      hint: "e^x 微分後是什麼？", diff: "easy", topic: "不定積分" },
    { q: "∫ 1/x dx = ?", a: "ln|x| + C", opts: ["ln|x| + C","1/x² + C","-1/x² + C","x⁻¹ + C"],
      explain: "∫1/x dx = ln|x| + C，注意要加絕對值符號，確保在 x<0 時也成立。",
      hint: "注意絕對值！", diff: "easy", topic: "不定積分" },
    { q: "∫ (2x + 3) dx = ?", a: "x² + 3x + C", opts: ["x² + 3x + C","2x² + 3x + C","x² + 3 + C","2 + C"],
      explain: "逐項積分：∫2x dx = x²，∫3 dx = 3x，合計 x² + 3x + C。",
      hint: "對每項分別積分", diff: "easy", topic: "不定積分" },
    { q: "∫ sin x dx = ?", a: "-cos x + C", opts: ["cos x + C","-cos x + C","sin x + C","-sin x + C"],
      explain: "∫sin x dx = -cos x + C，注意負號！（驗證：d/dx[-cos x] = sin x ✓）",
      hint: "注意積分結果的負號", diff: "easy", topic: "不定積分" },
  ],

  definite: [
    { q: "計算定積分：∫₀² x² dx = ?", a: "8/3", opts: ["4","8/3","2","4/3"],
      explain: "∫₀² x² dx = [x³/3]₀² = 2³/3 - 0³/3 = 8/3 - 0 = 8/3。",
      hint: "先求不定積分，再代入上下限相減", diff: "easy", topic: "定積分" },
    { q: "計算定積分：∫₀^π sin x dx = ?", a: "2", opts: ["0","1","2","π"],
      explain: "∫₀^π sin x dx = [-cos x]₀^π = -cos(π) - (-cos(0)) = -(-1) - (-1) = 1 + 1 = 2。",
      hint: "cos(π) = -1，cos(0) = 1", diff: "med", topic: "定積分" },
    { q: "計算定積分：∫₁² (3x² - 2x) dx = ?", a: "4", opts: ["2","4","6","8"],
      explain: "∫₁²(3x²-2x)dx = [x³-x²]₁² = (8-4)-(1-1) = 4-0 = 4。",
      hint: "先求反導函數 x³-x²，再代入上下限", diff: "med", topic: "定積分" },
  ],

  u_sub: [
    { q: "用換元法求：∫ 2x·e^(x²) dx，令 u = x²，結果為？", a: "e^(x²) + C",
      opts: ["e^(x²) + C","2x·e^(x²) + C","e^(2x) + C","x²·e^x + C"],
      explain: "令 u = x²，則 du = 2x dx。原積分 = ∫e^u du = e^u + C = e^(x²) + C。",
      hint: "令 u = x²，du = 2x dx", diff: "med", topic: "換元積分法" },
    { q: "求：∫ cos(3x) dx = ?", a: "sin(3x)/3 + C",
      opts: ["sin(3x)/3 + C","3sin(3x) + C","sin(3x) + C","cos(3x)/3 + C"],
      explain: "令 u = 3x，du = 3 dx，dx = du/3。原積分 = ∫cos(u)·(du/3) = sin(u)/3 + C = sin(3x)/3 + C。",
      hint: "令 u = 3x，注意要除以 3", diff: "med", topic: "換元積分法" },
    { q: "求：∫ x/(x²+1) dx = ?", a: "ln(x²+1)/2 + C",
      opts: ["ln(x²+1)/2 + C","ln(x²+1) + C","arctan(x) + C","1/2 · (x²+1) + C"],
      explain: "令 u = x²+1，du = 2x dx，x dx = du/2。∫(1/u)·(du/2) = (1/2)ln|u| + C = ln(x²+1)/2 + C。",
      hint: "令 u = x²+1，注意分子剛好接近 du", diff: "hard", topic: "換元積分法" },
  ],

  parts: [
    { q: "用分部積分求：∫ x·e^x dx = ?", a: "xe^x - e^x + C",
      opts: ["xe^x - e^x + C","xe^x + e^x + C","x²e^x/2 + C","e^x + C"],
      explain: "令 u=x, dv=e^x dx，則 du=dx, v=e^x。∫x·e^x dx = x·e^x - ∫e^x dx = xe^x - e^x + C。",
      hint: "分部積分：∫u dv = uv - ∫v du，令 u=x，dv=e^x dx", diff: "hard", topic: "分部積分" },
    { q: "用分部積分求：∫ x·cos x dx = ?", a: "x sin x + cos x + C",
      opts: ["x sin x + cos x + C","x sin x - cos x + C","x cos x + sin x + C","-x sin x + cos x + C"],
      explain: "令 u=x, dv=cos x dx，du=dx, v=sin x。∫x cos x dx = x sin x - ∫sin x dx = x sin x + cos x + C。",
      hint: "令 u=x，dv=cos x dx", diff: "hard", topic: "分部積分" },
  ],

  ftc: [
    { q: "微積分基本定理：若 F'(x) = f(x)，則 ∫_a^b f(x)dx = ?", a: "F(b) - F(a)",
      opts: ["F(a) - F(b)","F(b) - F(a)","F(b) + F(a)","f(b) - f(a)"],
      explain: "微積分基本定理第一部分：∫_a^b f(x)dx = F(b) - F(a)，其中 F 是 f 的任意一個反導函數。",
      hint: "代入上限減去代入下限", diff: "easy", topic: "微積分基本定理" },
    { q: "d/dx [∫₀^x cos(t²) dt] = ?", a: "cos(x²)",
      opts: ["cos(x²)","sin(x²)","2x cos(x²)","∫₀^x (-2t sin(t²)) dt"],
      explain: "微積分基本定理第二部分：d/dx[∫_a^x f(t)dt] = f(x)，直接把 t 換成 x 即可，得 cos(x²)。",
      hint: "FTC 第二部分：對積分上限的 x 求導，直接把 t 換成 x", diff: "hard", topic: "微積分基本定理" },
  ],
};

/* ── Topic Metadata ── */
const TOPICS_META = {
  limits:         { name: "極限" },
  lhopital:       { name: "L'Hôpital 法則" },
  continuity:     { name: "連續性" },
  derivative:     { name: "導數定義" },
  diff_rules:     { name: "微分法則" },
  chain_rule:     { name: "鏈鎖法則" },
  implicit:       { name: "隱函數微分" },
  integral_basic: { name: "不定積分" },
  definite:       { name: "定積分" },
  u_sub:          { name: "換元積分法" },
  parts:          { name: "分部積分" },
  ftc:            { name: "微積分基本定理" },
};
